
create table "Companies"
(
    "Id"           bigint generated by default as identity
        constraint "PK_Companies"
            primary key,
    "Title"        varchar(100),
    "Address"      varchar(200),
    "Status"       smallint  not null,
    "DateCreated"  timestamp not null,
    "DateModified" timestamp,
    "DateDeleted"  timestamp
);

alter table "Companies"
    owner to db_user_aih;

create table "Expenses"
(
    "Id"            bigint generated by default as identity
        constraint "PK_Expenses"
            primary key,
    "DateOfExpense" timestamp not null,
    "Money"         numeric   not null,
    "CompanyId"     bigint    not null
        constraint "FK_Expenses_Companies_CompanyId"
            references "Companies"
            on delete cascade,
    "Status"        smallint  not null,
    "DateCreated"   timestamp not null,
    "DateModified"  timestamp,
    "DateDeleted"   timestamp
);

alter table "Expenses"
    owner to db_user_aih;

create index "IX_Expenses_CompanyId"
    on "Expenses" ("CompanyId");

create table "Profits"
(
    "Id"           bigint generated by default as identity
        constraint "PK_Profits"
            primary key,
    "DateOfProfit" timestamp not null,
    "Money"        numeric   not null,
    "CompanyId"    bigint    not null
        constraint "FK_Profits_Companies_CompanyId"
            references "Companies"
            on delete cascade,
    "Status"       smallint  not null,
    "DateCreated"  timestamp not null,
    "DateModified" timestamp,
    "DateDeleted"  timestamp
);

alter table "Profits"
    owner to db_user_aih;

create index "IX_Profits_CompanyId"
    on "Profits" ("CompanyId");